// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71FZpc6qohyfmcow54-AubqL85tp_vEY',
    appId: '1:221256166720:web:12688055386a2816d3dea5',
    messagingSenderId: '221256166720',
    projectId: 'd2d-b2-utech',
    authDomain: 'd2d-b2-utech.firebaseapp.com',
    storageBucket: 'd2d-b2-utech.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARLXGeNiHI5A0TXWHgHW9QBtZLwzCRYRU',
    appId: '1:221256166720:android:e2fc80c2be88ab5ad3dea5',
    messagingSenderId: '221256166720',
    projectId: 'd2d-b2-utech',
    storageBucket: 'd2d-b2-utech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZR6JC-y-1ia5ZU0LFjxbts9n1WnUEa0',
    appId: '1:221256166720:ios:b16e62d1369389e0d3dea5',
    messagingSenderId: '221256166720',
    projectId: 'd2d-b2-utech',
    storageBucket: 'd2d-b2-utech.firebasestorage.app',
    iosBundleId: 'com.example.authtesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgZR6JC-y-1ia5ZU0LFjxbts9n1WnUEa0',
    appId: '1:221256166720:ios:b16e62d1369389e0d3dea5',
    messagingSenderId: '221256166720',
    projectId: 'd2d-b2-utech',
    storageBucket: 'd2d-b2-utech.firebasestorage.app',
    iosBundleId: 'com.example.authtesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC71FZpc6qohyfmcow54-AubqL85tp_vEY',
    appId: '1:221256166720:web:2d45a1177433ef18d3dea5',
    messagingSenderId: '221256166720',
    projectId: 'd2d-b2-utech',
    authDomain: 'd2d-b2-utech.firebaseapp.com',
    storageBucket: 'd2d-b2-utech.firebasestorage.app',
  );
}
